apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: wasm
  name: wasm
spec:
  containers:
  - image: sergioarmgpl/wasm-golang-edge:v1.0.0-1
    name: wasm
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}